### ISSUE TITLE
Cannot install to home directory

### ISSUE THREAD

**Issue by texttheater** [clab/dynet#755]
pip has a `--user` flag to install packages to the user’s home directory. This is very handy, especially if you are using a machine where you are not root. However, this fails with dynet (Ubuntu 16.04):

    $ pip install --user "git+https://github.com/clab/dynet#egg=dynet"
    Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
      Cloning https://github.com/clab/dynet to /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet
    Requirement already satisfied: cython in ./.local/lib/python2.7/site-packages (from dynet)
    Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages (from dynet)
    Installing collected packages: dynet
      Running setup.py install for dynet ... error
        Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/tmp.lvDrenZw1X/pip-xW6CJr-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
        running install
        running build
        INFO:root:==============================
        INFO:root:CMake path: /usr/bin/cmake
        INFO:root:Make path: /usr/bin/make
        INFO:root:Make flags: -j 4
        INFO:root:Mercurial path: /usr/bin/hg
        INFO:root:C compiler path: /usr/bin/gcc
        INFO:root:CXX compiler path: /usr/bin/g++
        INFO:root:---
        INFO:root:Script directory: /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet
        INFO:root:Build directory: /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit
        INFO:root:Library installation directory: /usr/lib/python2.7/dist-packages/../../..
        INFO:root:Python executable: /usr/bin/python
        INFO:root:==============================
        cmake version 3.5.1
        
        CMake suite maintained and supported by Kitware (kitware.com/cmake).
        g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
        Copyright (C) 2015 Free Software Foundation, Inc.
        This is free software; see the source for copying conditions.  There is NO
        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        
        INFO:root:Creating build directory /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit
        INFO:root:Cloning Eigen...
        destination directory: eigen
        applying clone bundle from https://media-api.atlassian.io/file/9cd0da8e-8d40-4d63-8a5a-1ed01de3f5a1/binary?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1MTRmMWY1ZC02YmRmLTQ2YmMtYmVhZC1hMTY4NTE2NzFmYTciLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjljZDBkYThlLThkNDAtNGQ2My04YTVhLTFlZDAxZGUzZjVhMSI6WyJyZWFkIl19LCJuYmYiOjE1MDE0OTIzMTAsImV4cCI6MTUwMTQ5MjczMH0.agNRDLpQ0z2rravw6Ax-7xCX_t3VT6Vg-l9tgW_3BII&client=514f1f5d-6bdf-46bc-bead-a16851671fa7
        adding changesets
        adding manifests
        adding file changes
        added 10390 changesets with 31555 changes to 2921 files (+5 heads)
        finished applying clone bundle
        searching for changes
        adding changesets
        adding manifests
        adding file changes
        added 152 changesets with 319 changes to 159 files
        updating to branch default
        1667 files updated, 0 files merged, 0 files removed, 0 files unresolved
        INFO:root:Configuring...
        -- The C compiler identification is GNU 5.4.0
        -- The CXX compiler identification is GNU 5.4.0
        -- Check for working C compiler: /usr/bin/gcc
        -- Check for working C compiler: /usr/bin/gcc -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Check for working CXX compiler: /usr/bin/g++
        -- Check for working CXX compiler: /usr/bin/g++ -- works
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- BACKEND not specified, defaulting to eigen.
        -- Eigen dir is /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit/eigen
        -- Looking for pthread.h
        -- Looking for pthread.h - found
        -- Looking for pthread_create
        -- Looking for pthread_create - not found
        -- Looking for pthread_create in pthreads
        -- Looking for pthread_create in pthreads - not found
        -- Looking for pthread_create in pthread
        -- Looking for pthread_create in pthread - found
        -- Found Threads: TRUE
        -- Found Cython version 0.25.2
        
        -- Configuring done
        -- Generating done
        -- Build files have been written to: /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit
        INFO:root:Compiling...
        Scanning dependencies of target dynet
        [  1%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
        [  3%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
        [  4%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
        [  6%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
        In file included from /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/dynet/aligned-mem-pool.cc:1:0:
        /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/dynet/aligned-mem-pool.h: In constructor ‘dynet::AlignedMemoryPool::AlignedMemoryPool(const string&, size_t, dynet::MemAllocator*, size_t)’:
        /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/dynet/aligned-mem-pool.h:65:12: warning: ‘dynet::AlignedMemoryPool::cap’ will be initialized after [-Wreorder]
             size_t cap;
                    ^
        /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/dynet/aligned-mem-pool.h:64:9: warning:   ‘int dynet::AlignedMemoryPool::current’ [-Wreorder]
             int current;
                 ^
        /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/dynet/aligned-mem-pool.cc:25:1: warning:   when initialized here [-Wreorder]
         AlignedMemoryPool::AlignedMemoryPool(const std::string &name, size_t initial_cap, MemAllocator *a, size_t expanding_unit) : name(name), cap(initial_cap), current(0), a(a), expanding_unit(expanding_unit) {
         ^
        [  7%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
        [  9%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o
        [ 10%] Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o
        [ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o
        [ 14%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o
        [ 15%] Building CXX object dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o
        [ 17%] Building CXX object dynet/CMakeFiles/dynet.dir/globals.cc.o
        [ 18%] Building CXX object dynet/CMakeFiles/dynet.dir/grad-check.cc.o
        [ 20%] Building CXX object dynet/CMakeFiles/dynet.dir/graph.cc.o
        [ 21%] Building CXX object dynet/CMakeFiles/dynet.dir/gru.cc.o
        [ 23%] Building CXX object dynet/CMakeFiles/dynet.dir/hsm-builder.cc.o
        [ 25%] Building CXX object dynet/CMakeFiles/dynet.dir/init.cc.o
        [ 26%] Building CXX object dynet/CMakeFiles/dynet.dir/io.cc.o
        [ 28%] Building CXX object dynet/CMakeFiles/dynet.dir/lstm.cc.o
        [ 29%] Building CXX object dynet/CMakeFiles/dynet.dir/mem.cc.o
        [ 31%] Building CXX object dynet/CMakeFiles/dynet.dir/model.cc.o
        [ 32%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-activations.cc.o
        [ 34%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-affinetransform.cc.o
        [ 35%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-const.cc.o
        [ 37%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-cwise.cc.o
        [ 39%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-scalar.cc.o
        [ 40%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-sum.cc.o
        [ 42%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-unary.cc.o
        [ 43%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-concat.cc.o
        [ 45%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-const.cc.o
        [ 46%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-contract.cc.o
        [ 48%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv.cc.o
        [ 50%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv2d.cc.o
        [ 51%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-dropout.cc.o
        [ 53%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-flow.cc.o
        [ 54%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-hinge.cc.o
        [ 56%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-linalg.cc.o
        [ 57%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-logsumexp.cc.o
        [ 59%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-losses.cc.o
        [ 60%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-lstm.cc.o
        [ 62%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-matrixmultiply.cc.o
        [ 64%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-maxpooling2d.cc.o
        [ 65%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-minmax.cc.o
        [ 67%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-moments.cc.o
        [ 68%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-normalization.cc.o
        [ 70%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-norms.cc.o
        [ 71%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-pickneglogsoftmax.cc.o
        [ 73%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-random.cc.o
        [ 75%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-select.cc.o
        [ 76%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-similarities.cc.o
        [ 78%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-softmaxes.cc.o
        [ 79%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-trig.cc.o
        [ 81%] Building CXX object dynet/CMakeFiles/dynet.dir/param-init.cc.o
        [ 82%] Building CXX object dynet/CMakeFiles/dynet.dir/param-nodes.cc.o
        [ 84%] Building CXX object dynet/CMakeFiles/dynet.dir/pretrain.cc.o
        [ 85%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn-state-machine.cc.o
        [ 87%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn.cc.o
        [ 89%] Building CXX object dynet/CMakeFiles/dynet.dir/saxe-init.cc.o
        [ 90%] Building CXX object dynet/CMakeFiles/dynet.dir/shadow-params.cc.o
        [ 92%] Building CXX object dynet/CMakeFiles/dynet.dir/tensor.cc.o
        [ 93%] Building CXX object dynet/CMakeFiles/dynet.dir/training.cc.o
        [ 95%] Building CXX object dynet/CMakeFiles/dynet.dir/treelstm.cc.o
        [ 96%] Building CXX object dynet/CMakeFiles/dynet.dir/weight-decay.cc.o
        [ 98%] Linking CXX shared library libdynet.so
        [ 98%] Built target dynet
        Scanning dependencies of target copy
        [ 98%] Built target copy
        Scanning dependencies of target target
        [100%] Generating timestamp
        running build_ext
        cythoning _dynet.pyx to _dynet.cpp
        building '_dynet' extension
        creating build
        creating build/temp.linux-x86_64-2.7
        /usr/bin/gcc -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet -I/tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit/eigen -I/usr/include/python2.7 -c _dynet.cpp -o build/temp.linux-x86_64-2.7/_dynet.o -std=c++11
        cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
        _dynet.cpp: In function ‘PyObject* __pyx_f_6_dynet_16LookupParameters_init_from_array(__pyx_obj_6_dynet_LookupParameters*, PyObject*, int)’:
        _dynet.cpp:14920:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           __pyx_t_7 = ((__pyx_t_6 > __pyx_v_self->thisptr.get_storage().values.size()) != 0);
                                   ^
        _dynet.cpp: In function ‘std::vector<unsigned int> __pyx_convert_vector_from_py_unsigned_int(PyObject*)’:
        _dynet.cpp:71524:87: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 __pyx_t_5 = __Pyx_PyInt_As_unsigned_int(__pyx_v_item); if (unlikely(__pyx_t_5 == -1 && PyErr_Occurred())) __PYX_ERR(1, 52, __pyx_L1_error)
                                                                                               ^
        _dynet.cpp:645:43: note: in definition of macro ‘unlikely’
           #define unlikely(x) __builtin_expect(!!(x), 0)
                                                   ^
        _dynet.cpp: At global scope:
        _dynet.cpp:8067:19: warning: ‘dynet::Dim __pyx_f_6_dynet_shape_as_c_dim(PyObject*, __pyx_opt_args_6_dynet_shape_as_c_dim*)’ defined but not used [-Wunused-function]
         static dynet::Dim __pyx_f_6_dynet_shape_as_c_dim(PyObject *__pyx_v_d, struct __pyx_opt_args_6_dynet_shape_as_c_dim *__pyx_optional_args) {
                           ^
        /usr/bin/g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_dynet.o -L. -L/tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit/dynet/ -Wl,-R/tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit/dynet/ -Wl,-R/usr/lib/ -ldynet -o /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/build/py2.7-64bit/python/_dynet.so
        [100%] Built target target
        INFO:root:Installing...
        [ 98%] Built target dynet
        [ 98%] Built target copy
        [100%] Built target target
        Install the project...
        -- Install configuration: ""
        CMake Error at dynet/cmake_install.cmake:36 (file):
          file cannot create directory: /usr/include/dynet.  Maybe need
          administrative privileges.
        Call Stack (most recent call first):
          cmake_install.cmake:37 (include)
        
        
        
        Makefile:61: recipe for target 'install' failed
        make: *** [install] Error 1
        error: /usr/bin/make install
        
        ----------------------------------------
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/tmp.lvDrenZw1X/pip-xW6CJr-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/tmp.lvDrenZw1X/pip-build-KlXxbM/dynet/

**Comment by neubig** [comment]
This may be fixed in a new version of pip, but for now I'd suggest using Anaconda or another virtualization environment, which will allow you to install without the `--user` command.

**Comment by neubig** [comment]
This is likely fixed as of this commit: https://github.com/clab/dynet/pull/783

Could you check if things work now?

**Comment by texttheater** [comment]
No, still fails:

    $ pip install --user "git+https://github.com/clab/dynet#egg=dynet"
    Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
      Cloning https://github.com/clab/dynet to /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet
    Requirement already satisfied: cython in ./.local/lib/python2.7/site-packages (from dynet)
    Requirement already satisfied: numpy in ./.local/lib/python2.7/site-packages (from dynet)
    Installing collected packages: dynet
      Running setup.py install for dynet ... error
        Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/tmp.GIS5kfrc9B/pip-fRQdPl-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
        running install
        running build
        INFO:root:CMAKE_PATH=/usr/bin/cmake
        INFO:root:MAKE_PATH=/usr/bin/make
        INFO:root:MAKE_FLAGS=-j 4
        INFO:root:HG_PATH=/usr/bin/hg
        INFO:root:EIGEN3_INCLUDE_DIR=/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/eigen
        INFO:root:CC_PATH=/usr/bin/gcc
        INFO:root:CXX_PATH=/usr/bin/g++
        INFO:root:SCRIPT_DIR=/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet
        INFO:root:BUILD_DIR=/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit
        INFO:root:INSTALL_PREFIX=/usr/lib/python2.7/dist-packages/../../..
        INFO:root:PYTHON=/usr/bin/python
        cmake version 3.5.1
        
        CMake suite maintained and supported by Kitware (kitware.com/cmake).
        g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
        Copyright (C) 2015 Free Software Foundation, Inc.
        This is free software; see the source for copying conditions.  There is NO
        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        
        INFO:root:Creating build directory /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit
        INFO:root:Cloning Eigen...
        destination directory: eigen
        applying clone bundle from https://media-api.atlassian.io/file/9cd0da8e-8d40-4d63-8a5a-1ed01de3f5a1/binary?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1MTRmMWY1ZC02YmRmLTQ2YmMtYmVhZC1hMTY4NTE2NzFmYTciLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjljZDBkYThlLThkNDAtNGQ2My04YTVhLTFlZDAxZGUzZjVhMSI6WyJyZWFkIl19LCJuYmYiOjE1MDMwNTcyNjcsImV4cCI6MTUwMzA1NzY4N30.noTPQHEv0dgb3G7jAPjd73tN82ktKaZ2Ttv42DBXbn4&client=514f1f5d-6bdf-46bc-bead-a16851671fa7
        adding changesets
        adding manifests
        adding file changes
        added 10390 changesets with 31555 changes to 2921 files (+5 heads)
        finished applying clone bundle
        searching for changes
        adding changesets
        adding manifests
        adding file changes
        added 162 changesets with 340 changes to 175 files
        updating to branch default
        1667 files updated, 0 files merged, 0 files removed, 0 files unresolved
        INFO:root:Configuring...
        -- The C compiler identification is GNU 5.4.0
        -- The CXX compiler identification is GNU 5.4.0
        -- Check for working C compiler: /usr/bin/gcc
        -- Check for working C compiler: /usr/bin/gcc -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Check for working CXX compiler: /usr/bin/g++
        -- Check for working CXX compiler: /usr/bin/g++ -- works
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- BACKEND not specified, defaulting to eigen.
        -- Eigen dir is /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/eigen
        -- Looking for pthread.h
        -- Looking for pthread.h - found
        -- Looking for pthread_create
        -- Looking for pthread_create - not found
        -- Looking for pthread_create in pthreads
        -- Looking for pthread_create in pthreads - not found
        -- Looking for pthread_create in pthread
        -- Looking for pthread_create in pthread - found
        -- Found Threads: TRUE
        -- Found Cython version 0.25.2
        
        CMAKE_INSTALL_PREFIX="/usr"
        PROJECT_SOURCE_DIR="/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet"
        PROJECT_BINARY_DIR="/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit"
        LIBS="-lpthread"
        EIGEN3_INCLUDE_DIR="/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/eigen"
        MKL_LINK_DIRS=""
        WITH_CUDA_BACKEND=""
        CUDA_RT_FILES=""
        CUDA_RT_DIRS=""
        CUDA_CUBLAS_FILES=""
        CUDA_CUBLAS_DIRS=""
        -- Configuring done
        -- Generating done
        -- Build files have been written to: /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit
        INFO:root:Compiling...
        Scanning dependencies of target dynet
        [  1%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
        [  4%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
        [  4%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
        [  6%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
        [  7%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
        [  9%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o
        [ 10%] Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o
        [ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o
        [ 13%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o
        [ 15%] Building CXX object dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o
        [ 16%] Building CXX object dynet/CMakeFiles/dynet.dir/globals.cc.o
        [ 18%] Building CXX object dynet/CMakeFiles/dynet.dir/grad-check.cc.o
        [ 20%] Building CXX object dynet/CMakeFiles/dynet.dir/graph.cc.o
        [ 21%] Building CXX object dynet/CMakeFiles/dynet.dir/gru.cc.o
        [ 23%] Building CXX object dynet/CMakeFiles/dynet.dir/hsm-builder.cc.o
        [ 24%] Building CXX object dynet/CMakeFiles/dynet.dir/init.cc.o
        [ 26%] Building CXX object dynet/CMakeFiles/dynet.dir/io.cc.o
        [ 27%] Building CXX object dynet/CMakeFiles/dynet.dir/lstm.cc.o
        [ 29%] Building CXX object dynet/CMakeFiles/dynet.dir/mem.cc.o
        [ 30%] Building CXX object dynet/CMakeFiles/dynet.dir/model.cc.o
        [ 32%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-activations.cc.o
        [ 33%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-affinetransform.cc.o
        [ 35%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-const.cc.o
        [ 36%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-cwise.cc.o
        [ 38%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-scalar.cc.o
        [ 40%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-sum.cc.o
        [ 41%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-unary.cc.o
        [ 43%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-concat.cc.o
        [ 44%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-const.cc.o
        [ 46%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-contract.cc.o
        [ 47%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv.cc.o
        [ 49%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv2d.cc.o
        [ 50%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-dropout.cc.o
        [ 52%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-flow.cc.o
        [ 53%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-hinge.cc.o
        [ 55%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-linalg.cc.o
        [ 56%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-logsumexp.cc.o
        [ 58%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-losses.cc.o
        [ 60%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-lstm.cc.o
        [ 61%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-matrixmultiply.cc.o
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc: In member function ‘virtual dynet::Dim dynet::VanillaLSTMGates::dim_forward(const std::vector<dynet::Dim>&) const’:
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:34:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(int i=0; i<num_inputs; i++){
                           ^
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc: In member function ‘virtual int dynet::VanillaLSTMGates::autobatch_sig(const dynet::ComputationGraph&, dynet::SigMap&) const’:
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:65:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for(int i=0; i<num_inputs; i++)
                             ^
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc: In instantiation of ‘void dynet::VanillaLSTMGates::forward_dev_impl(const MyDevice&, const std::vector<const dynet::Tensor*>&, dynet::Tensor&) const [with MyDevice = dynet::Device_CPU]’:
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:460:3:   required from here
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:135:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
               for(int i=0; i<num_inputs; i++){
                             ^
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc: In instantiation of ‘void dynet::VanillaLSTMGates::backward_dev_impl(const MyDevice&, const std::vector<const dynet::Tensor*>&, const dynet::Tensor&, const dynet::Tensor&, unsigned int, dynet::Tensor&) const [with MyDevice = dynet::Device_CPU]’:
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:460:3:   required from here
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:271:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int j=0; j<i; j++) offset += xs[j]->d[0];
                               ^
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:306:25: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                   for(int j=0; j<i; j++) offset += xs[j]->d[0];
                                 ^
        /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/nodes-lstm.cc:373:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 for(int i=0; i<num_inputs; i++){
                               ^
        [ 63%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-maxpooling2d.cc.o
        [ 64%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-minmax.cc.o
        [ 66%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-moments.cc.o
        [ 67%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-normalization.cc.o
        [ 69%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-norms.cc.o
        [ 70%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-pickneglogsoftmax.cc.o
        [ 72%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-random.cc.o
        [ 73%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-select.cc.o
        [ 75%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-similarities.cc.o
        [ 76%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-softmaxes.cc.o
        [ 78%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-to-device.cc.o
        [ 80%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-trig.cc.o
        [ 81%] Building CXX object dynet/CMakeFiles/dynet.dir/param-init.cc.o
        [ 83%] Building CXX object dynet/CMakeFiles/dynet.dir/param-nodes.cc.o
        [ 84%] Building CXX object dynet/CMakeFiles/dynet.dir/pretrain.cc.o
        [ 86%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn-state-machine.cc.o
        [ 87%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn.cc.o
        [ 89%] Building CXX object dynet/CMakeFiles/dynet.dir/saxe-init.cc.o
        [ 90%] Building CXX object dynet/CMakeFiles/dynet.dir/shadow-params.cc.o
        [ 92%] Building CXX object dynet/CMakeFiles/dynet.dir/tensor.cc.o
        [ 93%] Building CXX object dynet/CMakeFiles/dynet.dir/training.cc.o
        [ 95%] Building CXX object dynet/CMakeFiles/dynet.dir/treelstm.cc.o
        [ 96%] Building CXX object dynet/CMakeFiles/dynet.dir/weight-decay.cc.o
        [ 98%] Linking CXX shared library libdynet.so
        [ 98%] Built target dynet
        Scanning dependencies of target copy
        [ 98%] Built target copy
        Scanning dependencies of target target
        [100%] Generating timestamp
        running build_ext
        INFO:root:Building Cython extensions...
        INFO:root:INCLUDE_DIRS=/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/eigen
        INFO:root:LIBRARIES=dynet
        INFO:root:LIBRARY_DIRS=. /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/dynet/
        INFO:root:GPULIBRARIES=gdynet
        INFO:root:GPULIBRARY_DIRS=. /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/dynet/
        INFO:root:COMPILER_ARGS=-std=c++11
        INFO:root:EXTRA_LINK_ARGS=-Wl,-rpath=/usr/lib/,--no-as-needed
        INFO:root:RUNTIME_LIB_DIRS=/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/dynet/ /usr/lib/
        cythoning _dynet.pyx to _dynet.cpp
        building '_dynet' extension
        creating build
        creating build/temp.linux-x86_64-2.7
        /usr/bin/gcc -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet -I/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/eigen -I/usr/include/python2.7 -c _dynet.cpp -o build/temp.linux-x86_64-2.7/_dynet.o -std=c++11
        cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
        _dynet.cpp: In function ‘PyObject* __pyx_f_6_dynet_16LookupParameters_init_from_array(__pyx_obj_6_dynet_LookupParameters*, PyObject*, int)’:
        _dynet.cpp:15056:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           __pyx_t_7 = ((__pyx_t_6 > __pyx_v_self->thisptr.get_storage().values.size()) != 0);
                                   ^
        _dynet.cpp: In function ‘std::vector<unsigned int> __pyx_convert_vector_from_py_unsigned_int(PyObject*)’:
        _dynet.cpp:73363:87: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 __pyx_t_5 = __Pyx_PyInt_As_unsigned_int(__pyx_v_item); if (unlikely(__pyx_t_5 == -1 && PyErr_Occurred())) __PYX_ERR(1, 52, __pyx_L1_error)
                                                                                               ^
        _dynet.cpp:645:43: note: in definition of macro ‘unlikely’
           #define unlikely(x) __builtin_expect(!!(x), 0)
                                                   ^
        _dynet.cpp: At global scope:
        _dynet.cpp:8193:19: warning: ‘dynet::Dim __pyx_f_6_dynet_shape_as_c_dim(PyObject*, __pyx_opt_args_6_dynet_shape_as_c_dim*)’ defined but not used [-Wunused-function]
         static dynet::Dim __pyx_f_6_dynet_shape_as_c_dim(PyObject *__pyx_v_d, struct __pyx_opt_args_6_dynet_shape_as_c_dim *__pyx_optional_args) {
                           ^
        /usr/bin/g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/_dynet.o -L. -L/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/dynet/ -Wl,-R/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/dynet/ -Wl,-R/usr/lib/ -ldynet -o /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/build/py2.7-64bit/python/_dynet.so -Wl,-rpath=/usr/lib/,--no-as-needed
        INFO:root:Copying built extensions...
        [100%] Built target target
        INFO:root:Installing...
        [ 98%] Built target dynet
        [ 98%] Built target copy
        [100%] Built target target
        Install the project...
        -- Install configuration: ""
        -- Installing: /usr/include/dynet/aligned-mem-pool.h
        CMake Error at dynet/cmake_install.cmake:36 (file):
          file INSTALL cannot copy file
          "/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/dynet/aligned-mem-pool.h" to
          "/usr/include/dynet/aligned-mem-pool.h".
        Call Stack (most recent call first):
          cmake_install.cmake:37 (include)
        
        
        
        Makefile:61: recipe for target 'install' failed
        make: *** [install] Error 1
        error: /usr/bin/make install
        
        ----------------------------------------
    Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/tmp.GIS5kfrc9B/pip-fRQdPl-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/tmp.GIS5kfrc9B/pip-build-WVsY2x/dynet/

**Comment by neubig** [comment]
Hmm, OK, we'll take another look.

**Comment by danielhers** [comment]
It's running `make install` as part of the build, and `CMAKE_INSTALL_PREFIX="/usr"` is used based on the path of the `python` executable, which is not good since we're not superuser. Need for find a more robust way to determine the installation location, i.e. inside `~/.local` if `--user` is given.

**Comment by tuhinjubcse** [comment]
Hi 
danielhers 

Getting same issue

Installing collected packages: cython
Successfully installed cython-0.27
dyn-129-236-222-32:Desktop tuhinchakrabarty$ pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet
Requirement already satisfied: cython in /Library/Python/2.7/site-packages (from dynet)
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from dynet)
Installing collected packages: dynet
  Running setup.py install for dynet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-10ZzyH-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    INFO:root:CMAKE_PATH='/usr/local/bin/cmake'
    INFO:root:MAKE_PATH='/usr/bin/make'
    INFO:root:MAKE_FLAGS='-j 8'
    INFO:root:HG_PATH='/usr/local/bin/hg'
    INFO:root:EIGEN3_INCLUDE_DIR='/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/eigen'
    INFO:root:CC_PATH='/usr/bin/gcc'
    INFO:root:CXX_PATH='/usr/bin/g++'
    INFO:root:SCRIPT_DIR='/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet'
    INFO:root:BUILD_DIR='/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit'
    INFO:root:INSTALL_PREFIX='/Library/Python/2.7/site-packages/../../..'
    INFO:root:PYTHON='/usr/bin/python'
    cmake version 3.9.2
    
    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 8.1.0 (clang-802.0.42)
    Target: x86_64-apple-darwin16.5.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
    INFO:root:Creating build directory /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit
    INFO:root:Cloning Eigen...
    destination directory: eigen
    applying clone bundle from https://media-api.atlassian.io/file/9cd0da8e-8d40-4d63-8a5a-1ed01de3f5a1/binary?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiI1MTRmMWY1ZC02YmRmLTQ2YmMtYmVhZC1hMTY4NTE2NzFmYTciLCJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjljZDBkYThlLThkNDAtNGQ2My04YTVhLTFlZDAxZGUzZjVhMSI6WyJyZWFkIl19LCJuYmYiOjE1MDYyMzAwMjQsImV4cCI6MTUwNjIzMDQ0NH0.dspcb3NjMLRIL4OCrKupxvWGLQylaj7P5p-oEbDA8V0&client=514f1f5d-6bdf-46bc-bead-a16851671fa7
    adding changesets
    adding manifests
    adding file changes
    added 10390 changesets with 31555 changes to 2921 files (+5 heads)
    finished applying clone bundle
    searching for changes
    adding changesets
    adding manifests
    adding file changes
    added 219 changesets with 452 changes to 211 files
    updating to branch default
    1668 files updated, 0 files merged, 0 files removed, 0 files unresolved
    INFO:root:Configuring...
    -- The C compiler identification is AppleClang 8.1.0.8020042
    -- The CXX compiler identification is AppleClang 8.1.0.8020042
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/gcc
    -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- BACKEND not specified, defaulting to eigen.
    -- Eigen dir is /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/eigen
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    -- Found Cython version 0.27
    
    CMAKE_INSTALL_PREFIX="/Library"
    PROJECT_SOURCE_DIR="/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet"
    PROJECT_BINARY_DIR="/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit"
    LIBS=""
    EIGEN3_INCLUDE_DIR="/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/eigen"
    MKL_LINK_DIRS=""
    WITH_CUDA_BACKEND=""
    CUDA_RT_FILES=""
    CUDA_RT_DIRS=""
    CUDA_CUBLAS_FILES=""
    CUDA_CUBLAS_DIRS=""
    MSVC=""
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit
    INFO:root:Compiling...
    Scanning dependencies of target dynet
    [  1%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
    [  6%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
    [  6%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
    [  6%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
    [  7%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o
    [  9%] Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o
    [ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o
    [ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
    [ 13%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o
    [ 15%] Building CXX object dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o
    [ 16%] Building CXX object dynet/CMakeFiles/dynet.dir/globals.cc.o
    [ 18%] Building CXX object dynet/CMakeFiles/dynet.dir/grad-check.cc.o
    [ 20%] Building CXX object dynet/CMakeFiles/dynet.dir/graph.cc.o
    [ 21%] Building CXX object dynet/CMakeFiles/dynet.dir/gru.cc.o
    [ 23%] Building CXX object dynet/CMakeFiles/dynet.dir/hsm-builder.cc.o
    [ 24%] Building CXX object dynet/CMakeFiles/dynet.dir/init.cc.o
    [ 26%] Building CXX object dynet/CMakeFiles/dynet.dir/io.cc.o
    [ 27%] Building CXX object dynet/CMakeFiles/dynet.dir/lstm.cc.o
    [ 29%] Building CXX object dynet/CMakeFiles/dynet.dir/mem.cc.o
    [ 30%] Building CXX object dynet/CMakeFiles/dynet.dir/model.cc.o
    [ 32%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-activations.cc.o
    [ 33%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-affinetransform.cc.o
    [ 35%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-const.cc.o
    [ 36%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-cwise.cc.o
    [ 38%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-scalar.cc.o
    [ 40%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-sum.cc.o
    [ 41%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-arith-unary.cc.o
    [ 43%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-concat.cc.o
    [ 44%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-const.cc.o
    [ 46%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-contract.cc.o
    [ 47%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv.cc.o
    [ 49%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-conv2d.cc.o
    [ 50%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-dropout.cc.o
    [ 52%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-flow.cc.o
    [ 53%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-hinge.cc.o
    [ 55%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-linalg.cc.o
    [ 56%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-logsumexp.cc.o
    [ 58%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-losses.cc.o
    [ 60%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-lstm.cc.o
    [ 61%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-matrixmultiply.cc.o
    [ 63%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-maxpooling2d.cc.o
    [ 64%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-minmax.cc.o
    [ 66%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-moments.cc.o
    [ 67%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-normalization.cc.o
    [ 69%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-norms.cc.o
    [ 70%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-pickneglogsoftmax.cc.o
    [ 72%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-random.cc.o
    [ 73%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-select.cc.o
    [ 75%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-similarities.cc.o
    [ 76%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-softmaxes.cc.o
    [ 78%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-to-device.cc.o
    [ 80%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-trig.cc.o
    [ 81%] Building CXX object dynet/CMakeFiles/dynet.dir/param-init.cc.o
    [ 83%] Building CXX object dynet/CMakeFiles/dynet.dir/param-nodes.cc.o
    [ 84%] Building CXX object dynet/CMakeFiles/dynet.dir/pretrain.cc.o
    [ 86%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn-state-machine.cc.o
    [ 87%] Building CXX object dynet/CMakeFiles/dynet.dir/rnn.cc.o
    [ 89%] Building CXX object dynet/CMakeFiles/dynet.dir/saxe-init.cc.o
    [ 90%] Building CXX object dynet/CMakeFiles/dynet.dir/shadow-params.cc.o
    [ 92%] Building CXX object dynet/CMakeFiles/dynet.dir/tensor.cc.o
    [ 93%] Building CXX object dynet/CMakeFiles/dynet.dir/training.cc.o
    [ 95%] Building CXX object dynet/CMakeFiles/dynet.dir/treelstm.cc.o
    [ 96%] Building CXX object dynet/CMakeFiles/dynet.dir/weight-decay.cc.o
    [ 98%] Linking CXX shared library libdynet.dylib
    [ 98%] Built target dynet
    Scanning dependencies of target pydynet_precopy
    [ 98%] Built target pydynet_precopy
    Scanning dependencies of target pydynet
    [100%] Generating timestamp
    running build_ext
    INFO:root:Building Cython extensions...
    INFO:root:INCLUDE_DIRS='/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/eigen'
    INFO:root:LIBRARIES='dynet'
    INFO:root:LIBRARY_DIRS='. /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/dynet/'
    INFO:root:COMPILER_ARGS='-std=c++11 -Wno-unused-function -stdlib=libc++ -mmacosx-version-min=10.7'
    INFO:root:EXTRA_LINK_ARGS='-Wl,-rpath,/Library/lib/'
    INFO:root:RUNTIME_LIB_DIRS='/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/dynet/ /Library/lib/'
    cythoning _dynet.pyx to _dynet.cpp
    building '_dynet' extension
    creating build
    creating build/temp.macosx-10.12-intel-2.7
    /usr/bin/gcc -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -I/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet -I/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/eigen -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _dynet.cpp -o build/temp.macosx-10.12-intel-2.7/_dynet.o -std=c++11 -Wno-unused-function -stdlib=libc++ -mmacosx-version-min=10.7
    In file included from _dynet.cpp:543:
    /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/dynet/training.h:137:46: warning: implicit conversion loses integer precision: 'unsigned long' to 'unsigned int' [-Wshorten-64-to-32]
          return model->parameters_list().size() - aux_allocated;
          ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
    /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/dynet/training.h:140:53: warning: implicit conversion loses integer precision: 'unsigned long' to 'unsigned int' [-Wshorten-64-to-32]
          return model->lookup_parameters_list().size() - aux_allocated_lookup;
          ~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
    _dynet.cpp:6798:18: warning: implicit conversion loses integer precision: 'Py_ssize_t' (aka 'long') to 'int' [-Wshorten-64-to-32]
      __pyx_v_argc = __pyx_t_10;
                   ~ ^~~~~~~~~~
    _dynet.cpp:24755:58: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
      __pyx_t_1 = __Pyx_PyInt_From_int(__pyx_v_self->thisptr.parameter_count()); if (unlikely(!__pyx_t_1)) __PYX_ERR(0, 1213, __pyx_L1_error)
                  ~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
    _dynet.cpp:30564:27: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'unsigned int' [-Wshorten-64-to-32]
      __pyx_t_2 = __pyx_v_dm->num_devices();
                ~ ~~~~~~~~~~~~^~~~~~~~~~~~~
    _dynet.cpp:32707:26: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->vindex = __pyx_t_3;
                           ~ ^~~~~~~~~
    _dynet.cpp:38385:37: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->__pyx_base.vindex = __pyx_t_8;
                                      ~ ^~~~~~~~~
    _dynet.cpp:39076:37: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->__pyx_base.vindex = __pyx_t_13;
                                      ~ ^~~~~~~~~~
    _dynet.cpp:39617:37: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->__pyx_base.vindex = __pyx_t_12;
                                      ~ ^~~~~~~~~~
    _dynet.cpp:41407:37: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->__pyx_base.vindex = __pyx_t_6;
                                      ~ ^~~~~~~~~
    _dynet.cpp:41879:37: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->__pyx_base.vindex = __pyx_t_6;
                                      ~ ^~~~~~~~~
    _dynet.cpp:42601:37: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->__pyx_base.vindex = __pyx_t_5;
                                      ~ ^~~~~~~~~
    _dynet.cpp:43188:37: warning: implicit conversion loses integer precision: 'long' to 'dynet::VariableIndex' (aka 'unsigned int') [-Wshorten-64-to-32]
      __pyx_v_self->__pyx_base.vindex = __pyx_t_5;
                                      ~ ^~~~~~~~~
    13 warnings generated.
    /usr/bin/g++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.12-intel-2.7/_dynet.o -L. -L/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/dynet/ -L/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/dynet/ -L/Library/lib/ -ldynet -o /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/python/_dynet.so -Wl,-rpath,/Library/lib/
    ld: warning: directory not found for option '-L/Library/lib/'
    ld: warning: ignoring file /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/dynet//libdynet.dylib, file was built for x86_64 which is not the architecture being linked (i386): /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/build/py2.7-64bit/dynet//libdynet.dylib
    ld: warning: directory not found for option '-L/Library/lib/'
    INFO:root:Copying built extensions...
    [100%] Built target pydynet
    INFO:root:Installing...
    [ 98%] Built target dynet
    [ 98%] Built target pydynet_precopy
    [100%] Built target pydynet
    Install the project...
    -- Install configuration: "Release"
    CMake Error at dynet/cmake_install.cmake:31 (file):
      file cannot create directory: /Library/include/dynet.  Maybe need
      administrative privileges.
    Call Stack (most recent call first):
      cmake_install.cmake:32 (include)
    
    
    make: *** [install] Error 1
    error: /usr/bin/make install
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-10ZzyH-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_z/3nrgf_4s5p52485yv3pcs7gh0000gn/T/pip-build-LwdUVa/dynet/

**Comment by danielhers** [comment]
@tuhinjubcse you cannot install to the system Python without superuser permissions. That's true for any package.

**Comment by tuhinjubcse** [comment]
what do you suggest I do ?

**Comment by danielhers** [comment]
Create a virtualenv and install DyNet inside it: https://virtualenv.pypa.io/en/stable/
